[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = [
  "npm ci",
  "cd client && npm ci"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "npm run migrate:pg && npm start"
