[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm ci",
  "cd client && npm ci"
]

[phases.build]
cmds = [
  "rm -rf client/node_modules/.cache client/build",
  "cd client && CI=false GENERATE_SOURCEMAP=false npm run build"
]

[start]
cmd = "node server-minimal.js"
